<?php

# Control Settings
DEFINE("INI_TEST_MODE", true);#VERISIGN USER NAME

DEFINE("INI_MOD_REWRITE", false);#DB DATABASE NAME
DEFINE("INI_ENABLE_LOG", false);#DB DATABASE NAME
DEFINE("INI_ENABLE_TRACKING", false);#DB DATABASE NAME
DEFINE("INI_ADVANCED_TRACKING",false);#TRACK VISITS
DEFINE("INI_USE_COOKIES", "1");#USE COOKIES TO REMEMBER LOGGED USERS?
DEFINE("INI_COOKIE_EXPIRATION", 86400000);#COOKIES EXPIRE AFTER THIS PERIOD
DEFINE("APP_USE_EXTENDED_USER_SETTINGS",1);#USE EXTENDED USER SETTINGS - ADDITIONAL USER TABLE

# Content Settings
DEFINE("INI_SECRET_CODE", "abcde");#VERISIGN USER NAME
DEFINE("APP_TITLE", "Highland Farms, Grocery Stores, Toronto, York Region, GTA");#DB DATABASE NAME
DEFINE("APP_TITLE_SHORT", "Highland Farms Supermarkets");#DB DATABASE NAME

# Email Settings
DEFINE("EMAIL_FROM_ADDRESS", "lgrecu@thebrandfactory.com");#DB DATABASE NAME
DEFINE("EMAIL_FROM_NAME", "Highland Farms");#DB DATABASE NAME

# System Settings
DEFINE("APP_ADMIN_EMAIL", "lgrecu@thebrandfactory.com");#ADMIN EMAIL - SYSTEM EMAILS WILL BE SENT TO THIS ADDRESS
DEFINE("APP_BASE_DOMAIN","highlandfarms.ca");#BASE DOMAIN
DEFINE("APP_DOMAIN","highlandfarms.ca");#BASE DOMAIN INCLUDING SUBDIRECTORIES
DEFINE("APP_SERVER_NAME","http://www.highlandfarms.ca/");#HTTP ADDRESS
DEFINE("APP_SERVER_NAME_SECURE","https://www.highlandfarms.ca/");#HTTPS ADDRESS
DEFINE("APP_SITE_NAME","Highland Farms");#SITE ADDRESS IN NICE FORMAT (DISPLAY ONLY)
DEFINE("APP_BASE_PATH","d:/inetpub/www/highlandfarms.ca/");#APPLICATION BASE PATH
DEFINE("APP_CMS_PATH","http://www.highlandfarms.ca/");#APPLICATION BASE PATH

DEFINE("INI_DB_SERVER", "192.168.1.166");#DB SERVER NAME/IP ADDRESS
DEFINE("INI_DB_USER", "admin"); #DB USER NAME
DEFINE("INI_DB_PWD", "6xfjybxk");# DB PASSWORD
DEFINE("INI_DB_DB", "highland");#DB DATABASE NAME

DEFINE("APP_GOOGLE_API_KEY", 'ABQIAAAAkhIsL1cb4s_nBtpXYulOuBTplAeJXmY058aE1BpQStzwi0tqsRQiRZQ65zqUuAX2m51bwLK0EJfLuw');#DB DATABASE NAME
DEFINE("IM_PATH", 'C:\\Program Files\\ImageMagick\\');#DB DATABASE NAME
?>